name: flutter_referral_link
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_dynamic_links: ^5.4.15
  flutter:
    sdk: flutter

  get_ip_address: ^0.0.6
  go_router: ^13.2.0
  share: ^2.0.4
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
